version: "3.9"

services:
  eureka:
    image: service-registry
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - skillnet

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka:
        condition: service_started
    networks:
      - skillnet

  user-service:
    image: user-service
    container_name: user-service
    ports:
      - "9091:9091"
    depends_on:
      mysql:
        condition: service_started
      eureka:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      - skillnet
  job-service:
    image: job-service
    container_name: job-service
    ports:
      - "9092:9092"
    depends_on:
      kafka:
        condition: service_started
      mysql:
        condition: service_started
      eureka:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      - skillnet

  application-service:
    image: application-service
    container_name: application-service
    ports:
      - "9093:9093"
    depends_on:
      kafka:
        condition: service_started
      mysql:
        condition: service_started
      eureka:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      - skillnet
  
  notification-service:
    image: notification-service
    container_name: notification-service
    ports:
      - "9094:9094"
    depends_on:
      kafka:
        condition: service_started
      mysql:
        condition: service_started
      eureka:
        condition: service_started
      api-gateway:
        condition: service_started
    networks:
      - skillnet
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jobapplication
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - skillnet
  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9192:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - skillnet
  ui:
    image: ui
    container_name: ui
    ports:
      - "5173:5173"
    depends_on:
      api-gateway:
        condition: service_started
    networks:
      - skillnet

networks:
  skillnet:

volumes:
  mysql_data:
  kafka_data:
