server:
  port: 9091

spring:
  application:
    name: user-service
  datasource:
    url: databaseurl
    username: username
    password: password
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka

jwt:
  secret: your_secret_key
